(TeX-add-style-hook
 "MathFactsList"
 (lambda ()
   (TeX-run-style-hooks
    "latex2e"
    "handout"
    "handout10"
    "econark"
    "handoutSetup"
    "handoutShortcuts")
   (TeX-add-symbols
    "CRRALim"
    "FinSum"
    "InfSum"
    "FinSumMult"
    "InfSumMult"
    "TaylorOne"
    "TaylorTwo"
    "SmallSmallZero"
    "LogEps"
    "ExpEps"
    "OverPlus"
    "MultPlus"
    "ExpPlus"
    "SumNormsIsNorm"
    "ELogNorm"
    "LogELogNorm"
    "ELogNormMeanOne"
    "MeanOne"
    "LogMeanMPS"
    "NormTimes"
    "ELogNormTimes"
    "LogELogNormTimes"
    "EulersTheorem")
   (LaTeX-add-labels
    "CRRALim"
    "fact:CRRALim"
    "fact:FinSum"
    "fact:InfSum"
    "fact:FinSumMult"
    "fact:InfSumMult"
    "fact:TaylorOne"
    "fact:TaylorTwo"
    "fact:SmallSmallZero"
    "fact:LogEps"
    "eq:SumNormsIsNorm"
    "eq:ELogNorm"
    "eq:ELogNormMeanOne"
    "eq:riskyELev"
    "eq:riskyELog"
    "NormTimes"
    "eq:ELogNormTimes"
    "eq:LogELogNormTimes"
    "fact:EulersTheorem")
   (LaTeX-add-environments
    "defn"
    "Fact"))
 :latex)

